name: Rails CI

on:
  push:

jobs:
  test:
    name: Run Tests and Linter
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: simple_mailer_test
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --without development

      - name: Set up database
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load

      - name: Run RSpec tests
        run: bundle exec rspec
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:password@localhost:5432/simple_mailer_test

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./spec/reports # Adjust the path based on your configuration
